/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e4e2e4",
        "secondary-fixed-dim": "#b7c8e1",
        "on-primary-fixed": "#131b2e",
        "inverse-primary": "#bec6e0",
        "tertiary": "#000000",
        "on-secondary-container": "#54647a",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-fixed": "#0b1c30",
        "on-tertiary-fixed-variant": "#574425",
        "surface-container-low": "#f6f3f5",
        "background": "#fcf8fa",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#131b2e",
        "outline-variant": "#c6c6cd",
        "secondary-fixed": "#d3e4fe",
        "inverse-on-surface": "#f3f0f2",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#fcdeb5",
        "on-primary": "#ffffff",
        "surface-bright": "#fcf8fa",
        "on-tertiary-fixed": "#271901",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-highest": "#e4e2e4",
        "surface": "#fcf8fa",
        "on-background": "#1b1b1d",
        "secondary": "#505f76",
        "tertiary-fixed-dim": "#dec29a",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "error": "#ba1a1a",
        "tertiary-container": "#271901",
        "on-surface": "#1b1b1d",
        "on-error-container": "#93000a",
        "surface-container-high": "#eae7e9",
        "on-surface-variant": "#45464d",
        "on-primary-container": "#7c839b",
        "surface-tint": "#565e74",
        "primary-fixed": "#dae2fd",
        "on-error": "#ffffff",
        "inverse-surface": "#303032",
        "surface-dim": "#dcd9db",
        "on-tertiary-container": "#98805d",
        "outline": "#76777d",
        "secondary-container": "#d0e1fb",
        "surface-container": "#f0edef",
        "primary": "#000000",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        gutter: "1rem",
        margin: "2rem",
      },
      fontFamily: {
        h1: ["Inter", "ui-sans-serif", "system-ui"],
        h2: ["Inter", "ui-sans-serif", "system-ui"],
        h3: ["Inter", "ui-sans-serif", "system-ui"],
        "body-lg": ["Inter", "ui-sans-serif", "system-ui"],
        "body-md": ["Inter", "ui-sans-serif", "system-ui"],
        "body-sm": ["Inter", "ui-sans-serif", "system-ui"],
        "label-md": ["Inter", "ui-sans-serif", "system-ui"],
        "data-mono": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"],
      },
      fontSize: {
        h1: ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        h2: ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3: ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
