/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#b6ecf5",
        "inverse-surface": "#2e3131",
        "secondary-fixed": "#ffdad9",
        "on-secondary-fixed-variant": "#773033",
        "inverse-on-surface": "#f0f1f1",
        "on-primary-fixed-variant": "#134e56",
        "on-error-container": "#93000a",
        "outline-variant": "#bfc8c9",
        "on-tertiary-fixed": "#261900",
        "surface-tint": "#30666e",
        "surface-bright": "#f8f9fa",
        "tertiary-container": "#846524",
        "surface-container-low": "#f3f4f4",
        "surface-container": "#edeeee",
        "on-surface": "#191c1c",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d9dada",
        "on-surface-variant": "#40484a",
        "surface-variant": "#e1e3e3",
        "on-tertiary-fixed-variant": "#5d4201",
        "on-secondary-fixed": "#3d050b",
        "secondary-container": "#ff9e9f",
        "on-secondary-container": "#7a3235",
        "tertiary-fixed-dim": "#e9c176",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "outline": "#70797a",
        "primary-fixed-dim": "#9acfd8",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container-highest": "#e1e3e3",
        "background": "#f8f9fa",
        "on-primary-fixed": "#001f24",
        "secondary": "#944749",
        "primary": "#225961",
        "surface": "#f8f9fa",
        "inverse-primary": "#9acfd8",
        "on-background": "#191c1c",
        "on-primary-container": "#bef5fe",
        "tertiary": "#694d0c",
        "on-secondary": "#ffffff",
        "primary-container": "#3d727a",
        "on-tertiary-container": "#ffe8c3",
        "tertiary-fixed": "#ffdea5",
        "surface-container-high": "#e7e8e8",
        "secondary-fixed-dim": "#ffb3b2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        gutter: "1rem",
        margin: "2rem",
      },
      fontFamily: {
        h1: ["Inter", "ui-sans-serif", "system-ui"],
        h2: ["Inter", "ui-sans-serif", "system-ui"],
        h3: ["Inter", "ui-sans-serif", "system-ui"],
        "body-lg": ["Inter", "ui-sans-serif", "system-ui"],
        "body-md": ["Inter", "ui-sans-serif", "system-ui"],
        "body-sm": ["Inter", "ui-sans-serif", "system-ui"],
        "label-md": ["Inter", "ui-sans-serif", "system-ui"],
        "data-mono": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "Liberation Mono", "Courier New", "monospace"],
      },
      fontSize: {
        h1: ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        h2: ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3: ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
}
